### ISSUE TITLE
Add audible alerts to notifications

### ISSUE THREAD

**Issue by waynedyck** [WSDOT/wsdot-ios-app#218]
Notifications would produce an audible sound similar to when text messages are received.

**Comment by englehorn** [comment]
iOS app notifications are set up to use the default notification sound assigned in the firebase messaging push_notifications.py payload.

https://github.com/WSDOT/firebase-messaging-app/blob/833ac9c13eed39eb3b7f9ca88de73f1bfff616c8/push_notifications.py#L133

**Comment by englehorn** [comment]
Closing this issue. The notification sounds have been working for me in testing. 

In order for the notification sounds to work:
1. The notification sounds must be selected in app settings. 
2. The app must be closed or in a background state.
