### ISSUE TITLE
Complaints about the app not updating to reflect current WSF website information

### ISSUE THREAD

**Issue by waynedyck** [WSDOT/wsdot-ios-app#223]
Web agent feedback about the Alerts not updated on the App. Based on one test (iPhone 8), the most recent alert took ~ 20 minutes to be updated on the Ferries App.

User even turned Off and On the background refresh, and Off the phone and turned it back On.

**Comment by waynedyck** [comment]
I am seeing the latest alerts, however, the timestamp appears to be off. The Android app appears to be displaying the last update time correctly. Need check which fields from the data feed we are using in the iOS app.

Also need to monitor the website for new alerts and how long it takes those alerts to show up in the data files and then the app itself.

**Comment by englehorn** [comment]
- Ferry schedule data is now updating about every 5-15 minutes. 
- iOS v5.30.0 & Android v6.16.0 restores the 7-day ferry schedule calendar and adds an informational button with a link to the Washington State Ferry website. 

Related to: 
- iOS https://github.com/WSDOT/wsdot-ios-app/issues/241

- Android https://github.com/WSDOT/wsdot-kotlin-app/issues/137
- Android https://github.com/WSDOT/wsdot-kotlin-app/issues/143
- Android https://github.com/WSDOT/wsdot-kotlin-app/issues/132
