### ISSUE TITLE
Add camera direction UILabel

### ISSUE THREAD

**Issue by englehorn** [WSDOT/wsdot-ios-app#265]
The mobile API camera data is returning null for all camera direction values. It can be removed from the camera view layout.

**Comment by englehorn** [comment]
@waynedyck commented on this issue here https://github.com/englehorn/wsdot-ios-app/commit/21c8136c5d917119358b1ad6dd5285061a966698#commitcomment-81234571

The camera view controller UI now uses stack views. To re-enable the direction label it will need to be added to the stack view underneath the camera image.

**Comment by waynedyck** [comment]
Set camera direction again with commit https://github.com/WSDOT/mobile-app-data-scripts/commit/48b6cfc8e8fa226307455d81442f3708e69d100f

**Comment by englehorn** [comment]
Will be restoring camera direction label & adding refresh rate label with next app update.
